image: node:15-buster

stages:
    - build

before_script:
    - apt-get update
    - apt-get install zip

build:
    stage: build
    script:
        - zip pdftostill.zip -r pdftostill
        - mkdir static_module
        - cp pdftostill/module.json static_module
    artifacts:
        paths:
            - pdftostill.zip
            - static_module/module.json
